create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    kakao_id text not null unique,
    nickname text not null,
    profile_image_url text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.user_settings (
    user_id uuid primary key references public.profiles(id) on delete cascade,
    deadline_time time not null default '08:30',
    delay_minutes integer not null default 5,
    push_enabled boolean not null default true,
    relation_push_enabled boolean not null default true,
    missed_push_enabled boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint user_settings_delay_minutes_check check (delay_minutes > 0)
);

create table if not exists public.guardian_relations (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.profiles(id) on delete cascade,
    guardian_user_id uuid references public.profiles(id) on delete set null,
    guardian_name text not null,
    relation text not null,
    status text not null default 'pending',
    invite_code text not null unique,
    created_at timestamptz not null default now(),
    accepted_at timestamptz,
    constraint guardian_relations_status_check check (status in ('pending', 'accepted', 'rejected'))
);

create table if not exists public.check_ins (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.profiles(id) on delete cascade,
    checked_at timestamptz not null default now(),
    created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.user_settings enable row level security;
alter table public.guardian_relations enable row level security;
alter table public.check_ins enable row level security;

create policy profiles_select_own on public.profiles for select using (auth.uid() = id);
create policy profiles_insert_own on public.profiles for insert with check (auth.uid() = id);
create policy profiles_update_own on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

create policy user_settings_select_own on public.user_settings for select using (auth.uid() = user_id);
create policy user_settings_insert_own on public.user_settings for insert with check (auth.uid() = user_id);
create policy user_settings_update_own on public.user_settings for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy guardian_relations_select_related on public.guardian_relations for select using (auth.uid() = user_id or auth.uid() = guardian_user_id);
create policy guardian_relations_insert_own on public.guardian_relations for insert with check (auth.uid() = user_id);
create policy guardian_relations_update_related on public.guardian_relations for update using (auth.uid() = user_id or auth.uid() = guardian_user_id);

create policy check_ins_select_related on public.check_ins for select using (
    auth.uid() = user_id or exists (
        select 1 from public.guardian_relations gr
        where gr.user_id = check_ins.user_id
          and gr.guardian_user_id = auth.uid()
          and gr.status = 'accepted'
    )
);
create policy check_ins_insert_own on public.check_ins for insert with check (auth.uid() = user_id);

create index if not exists guardian_relations_user_id_idx on public.guardian_relations(user_id);
create index if not exists guardian_relations_guardian_user_id_idx on public.guardian_relations(guardian_user_id);
create index if not exists check_ins_user_id_checked_at_idx on public.check_ins(user_id, checked_at desc);
