create extension if not exists pg_cron with schema extensions;
create extension if not exists pg_net with schema extensions;

alter table public.check_ins
    add column if not exists check_in_date date not null default ((now() at time zone 'Asia/Seoul')::date);

create unique index if not exists check_ins_user_date_key
    on public.check_ins(user_id, check_in_date);

create table if not exists public.push_tokens (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.profiles(id) on delete cascade,
    token text not null unique,
    platform text not null,
    device_id text,
    enabled boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    last_seen_at timestamptz not null default now(),
    constraint push_tokens_platform_check check (platform in ('android', 'ios'))
);

create table if not exists public.notification_events (
    id uuid primary key default gen_random_uuid(),
    recipient_user_id uuid not null references public.profiles(id) on delete cascade,
    actor_user_id uuid references public.profiles(id) on delete set null,
    event_type text not null,
    title text not null,
    body text not null,
    related_user_id uuid references public.profiles(id) on delete set null,
    guardian_relation_id bigint references public.guardian_relations(id) on delete set null,
    check_in_date date,
    status text not null default 'pending',
    sent_at timestamptz,
    read_at timestamptz,
    fcm_message_id text,
    error_message text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint notification_events_type_check check (
        event_type in ('missed_check_in', 'guardian_request', 'relation_accepted')
    ),
    constraint notification_events_status_check check (
        status in ('pending', 'sent', 'failed', 'read')
    )
);

create unique index if not exists notification_events_missed_unique
    on public.notification_events(recipient_user_id, actor_user_id, event_type, check_in_date)
    where event_type = 'missed_check_in' and check_in_date is not null;

create index if not exists push_tokens_user_id_idx
    on public.push_tokens(user_id);

create index if not exists notification_events_recipient_created_idx
    on public.notification_events(recipient_user_id, created_at desc);

do $$
begin
    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'invite_links'
          and column_name = 'used_by_user_id'
    ) then
        create index if not exists invite_links_used_by_user_id_idx
            on public.invite_links(used_by_user_id);
    end if;
end $$;

alter table public.push_tokens enable row level security;
alter table public.notification_events enable row level security;

drop policy if exists push_tokens_owner_all on public.push_tokens;
create policy push_tokens_select_own
    on public.push_tokens
    for select
    to authenticated
    using ((select auth.uid()) = user_id);

create policy push_tokens_insert_own
    on public.push_tokens
    for insert
    to authenticated
    with check ((select auth.uid()) = user_id);

create policy push_tokens_update_own
    on public.push_tokens
    for update
    to authenticated
    using ((select auth.uid()) = user_id)
    with check ((select auth.uid()) = user_id);

create policy push_tokens_delete_own
    on public.push_tokens
    for delete
    to authenticated
    using ((select auth.uid()) = user_id);

create policy notification_events_select_recipient
    on public.notification_events
    for select
    to authenticated
    using ((select auth.uid()) = recipient_user_id);

create policy notification_events_update_recipient
    on public.notification_events
    for update
    to authenticated
    using ((select auth.uid()) = recipient_user_id)
    with check ((select auth.uid()) = recipient_user_id);

grant select, insert, update, delete on public.push_tokens to authenticated;
grant select, update on public.notification_events to authenticated;

drop policy if exists profiles_select_own on public.profiles;
drop policy if exists profiles_insert_own on public.profiles;
drop policy if exists profiles_update_own on public.profiles;
drop policy if exists profiles_select_active_invite_owner on public.profiles;
drop policy if exists profiles_select_accepted_guardian on public.profiles;

create policy profiles_select_own
    on public.profiles
    for select
    to authenticated
    using ((select auth.uid()) = id);

create policy profiles_insert_own
    on public.profiles
    for insert
    to authenticated
    with check ((select auth.uid()) = id);

create policy profiles_update_own
    on public.profiles
    for update
    to authenticated
    using ((select auth.uid()) = id)
    with check ((select auth.uid()) = id);

create policy profiles_select_active_invite_owner
    on public.profiles
    for select
    to authenticated
    using (
        exists (
            select 1
            from public.invite_links il
            where il.owner_user_id = profiles.id
              and il.status = 'active'
        )
    );

create policy profiles_select_accepted_guardian
    on public.profiles
    for select
    to authenticated
    using (
        exists (
            select 1
            from public.guardian_relations gr
            where gr.user_id = profiles.id
              and gr.guardian_user_id = (select auth.uid())
              and gr.status = 'accepted'
        )
    );

drop policy if exists user_settings_select_own on public.user_settings;
drop policy if exists user_settings_insert_own on public.user_settings;
drop policy if exists user_settings_update_own on public.user_settings;

create policy user_settings_select_own
    on public.user_settings
    for select
    to authenticated
    using ((select auth.uid()) = user_id);

create policy user_settings_insert_own
    on public.user_settings
    for insert
    to authenticated
    with check ((select auth.uid()) = user_id);

create policy user_settings_update_own
    on public.user_settings
    for update
    to authenticated
    using ((select auth.uid()) = user_id)
    with check ((select auth.uid()) = user_id);

drop policy if exists invite_links_owner_all on public.invite_links;
drop policy if exists invite_links_accept_read on public.invite_links;

create policy invite_links_select_related
    on public.invite_links
    for select
    to authenticated
    using (
        owner_user_id = (select auth.uid())
        or status = 'active'
    );

create policy invite_links_insert_own
    on public.invite_links
    for insert
    to authenticated
    with check (owner_user_id = (select auth.uid()));

create policy invite_links_update_owner
    on public.invite_links
    for update
    to authenticated
    using (owner_user_id = (select auth.uid()))
    with check (owner_user_id = (select auth.uid()));

drop policy if exists guardian_relations_select_related on public.guardian_relations;
drop policy if exists guardian_relations_insert_own on public.guardian_relations;
drop policy if exists guardian_relations_update_related on public.guardian_relations;
drop policy if exists guardian_relations_participant_read on public.guardian_relations;
drop policy if exists guardian_relations_owner_insert on public.guardian_relations;
drop policy if exists guardian_relations_participant_update on public.guardian_relations;
drop policy if exists guardian_relations_guardian_accept_insert on public.guardian_relations;

create policy guardian_relations_participant_read
    on public.guardian_relations
    for select
    to authenticated
    using ((select auth.uid()) = user_id or (select auth.uid()) = guardian_user_id);

create policy guardian_relations_owner_insert
    on public.guardian_relations
    for insert
    to authenticated
    with check ((select auth.uid()) = user_id);

create policy guardian_relations_guardian_accept_insert
    on public.guardian_relations
    for insert
    to authenticated
    with check (
        (select auth.uid()) = guardian_user_id
        and status = 'accepted'
        and exists (
            select 1
            from public.invite_links il
            where il.id = invite_link_id
              and il.invite_code = guardian_relations.invite_code
              and il.owner_user_id = guardian_relations.user_id
              and il.status = 'active'
        )
    );

create policy guardian_relations_participant_update
    on public.guardian_relations
    for update
    to authenticated
    using ((select auth.uid()) = user_id or (select auth.uid()) = guardian_user_id)
    with check ((select auth.uid()) = user_id or (select auth.uid()) = guardian_user_id);

drop policy if exists check_ins_select_related on public.check_ins;
drop policy if exists check_ins_insert_own on public.check_ins;
drop policy if exists check_ins_owner_all on public.check_ins;

create policy check_ins_select_related
    on public.check_ins
    for select
    to authenticated
    using (
        (select auth.uid()) = user_id
        or exists (
            select 1
            from public.guardian_relations gr
            where gr.user_id = check_ins.user_id
              and gr.guardian_user_id = (select auth.uid())
              and gr.status = 'accepted'
        )
    );

create policy check_ins_insert_own
    on public.check_ins
    for insert
    to authenticated
    with check ((select auth.uid()) = user_id);

create or replace function public.process_missed_check_ins()
returns table (
    event_id uuid,
    recipient_user_id uuid,
    related_user_id uuid,
    token text,
    platform text,
    title text,
    body text
)
language sql
security definer
set search_path = public
as $$
    with due_users as (
        select
            us.user_id,
            us.deadline_time,
            us.delay_minutes,
            ((now() at time zone 'Asia/Seoul')::date) as check_date
        from public.user_settings us
        where us.push_enabled = true
          and us.missed_push_enabled = true
          and (now() at time zone 'Asia/Seoul') >= (
              ((now() at time zone 'Asia/Seoul')::date + us.deadline_time)
              + make_interval(mins => us.delay_minutes)
          )
          and not exists (
              select 1
              from public.check_ins ci
              where ci.user_id = us.user_id
                and ci.check_in_date = ((now() at time zone 'Asia/Seoul')::date)
          )
    ),
    inserted as (
        insert into public.notification_events (
            recipient_user_id,
            actor_user_id,
            event_type,
            title,
            body,
            related_user_id,
            guardian_relation_id,
            check_in_date
        )
        select
            gr.guardian_user_id,
            du.user_id,
            'missed_check_in',
            p.nickname || '님 안부 미확인',
            du.deadline_time::text || '까지 안부 확인이 없었어요.',
            du.user_id,
            gr.id,
            du.check_date
        from due_users du
        join public.guardian_relations gr
          on gr.user_id = du.user_id
         and gr.status = 'accepted'
         and gr.guardian_user_id is not null
        join public.profiles p
          on p.id = du.user_id
        join public.user_settings guardian_settings
          on guardian_settings.user_id = gr.guardian_user_id
         and guardian_settings.push_enabled = true
         and guardian_settings.missed_push_enabled = true
        on conflict do nothing
        returning id, recipient_user_id, title, body
    )
    select
        ne.id,
        ne.recipient_user_id,
        ne.related_user_id,
        pt.token,
        pt.platform,
        ne.title,
        ne.body
    from public.notification_events ne
    join public.push_tokens pt
      on pt.user_id = ne.recipient_user_id
     and pt.enabled = true
    where ne.status in ('pending', 'failed')
      and ne.event_type = 'missed_check_in'
      and ne.check_in_date = ((now() at time zone 'Asia/Seoul')::date);
$$;

revoke all on function public.process_missed_check_ins() from public;

select cron.unschedule('process-missed-check-ins')
where exists (
    select 1
    from cron.job
    where jobname = 'process-missed-check-ins'
);

select cron.schedule(
    'process-missed-check-ins',
    '*/5 * * * *',
    $$
    select net.http_post(
        url := (select decrypted_secret from vault.decrypted_secrets where name = 'livving_project_url')
            || '/functions/v1/process-missed-check-ins',
        headers := jsonb_build_object(
            'Content-Type', 'application/json',
            'x-livving-cron-secret', (select decrypted_secret from vault.decrypted_secrets where name = 'livving_cron_secret')
        ),
        body := jsonb_build_object('scheduled_at', now())
    );
    $$
);
